namespace: local
name: zinit
version: 1.0.0
readme: README.md
authors:
  - Scott Yeager
license: MIT
repository: https://github.com/scottyeager/ansible-zinit
description: Zinit service management collection
tags:
  - zinit
  - service
  - init
dependencies: {}
